FROM node:18-alpine

WORKDIR /usr/src/app

# Install OpenSSL and other dependencies
RUN apk add --no-cache openssl openssl-dev curl

RUN pwd

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install -g @nestjs/cli
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3000
