import { INVALID_CREDENTIAL } from "@/constants/error";
import { IsString } from "class-validator";
import { ApiProperty } from "@nestjs/swagger";

export class SigninInput {
    @ApiProperty({ description: 'Username generated by admin', example: 'john2025' })
    @IsString({ message: INVALID_CREDENTIAL })
    username: string;
}
